apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: Kafka-User
  namespace: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Define ACLs to grant permissions for the user
      - resource:
          type: topic
          name: 
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Write
