apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  authentication:
    type: none
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: group-messages
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
      - resource:
          type: 
          name: one-to-one-messages
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
