---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgBl+RCmTMpwslFfWbvdF6FOlsacykxO9V9rPEbuMvg8NT5bjzcaQbVWgQb4YDt9k0znFDPgru9+Dj2zJ6LZ5GVTCvThUwybLewl0aenyxGwv9at/Zoz1rmzj07Kr5R1/VUQM2Vbs+lNAlpNLN4Yo8D7DKbcM0IrSNQfkgMowUCUYl9/yDywBDLU/NiroPK3aC7FCFu1Ljc9p/OhoBNDipcT7CtZnF7+6tY2+ujXjZy003KrU0y3/ooqXPxa52wr/0Xxw6+cg5cLWVgWt9KZMI5QnPvzlyLbiNpU8w1hSRMmlBRHGlmf8SNsiho8Wnij+IVrAZXS55Xo2TyjJ3/aUGB/sRYnsK54ZueXJ/0rpzDfSj45r4v7mtwrcZ7HPmBJOgRrGt7xTk0qgajrdTrCd/DQWB4k+tP4XzJE4ucJNOHhnNDaeKnPG1Ydsvu9iuPdkf+gQqWOfajRMT7GXuIq5aWQ0R9s75biMW7s97GIyEhsOyN1guVI1ledUxdaiKBtPicw+3xz+MNKpe1LNDYbEnovQDkfWPfvYs1mgP4MgECx3AS8+5MpntMJ/N5hEDiKZfuC9uM60ZulGr9dQndabPdbAKuG2GbCrydtGuoQGucgF9Rk5UQgEv19LfXxF3N+lzZG5IV9gnhvw0sglTVTP8AIfuCegyfbdEOabYvw+YNSZjemoa1YipkJP8thQho8h1Pj/FsueCbeRSU=
    username: AgAke+rj0Ro/YE+nuSTlzmHVfQW1VwY/ELj15V4kbOHcVhvsqMoLQ2fPGMQgDd7PQJudgnMkqRNVF+LD3eMUM2xurNLE0/gd4ouiSKCJrGtNOFG07KZ2FaUi0ViIj8UlHOPh7HWIYI7SoMGnzBlTvUIne7KKsnhx+7FTj6C/rZo5HcWZFIkXMIUxIwCQ3zGPCd1KtAC872fyXrwjHsvvB6lZdljvxN56Ov6Xb6zt6fyV7FjVR1YVQNEprkJM5h9nV9ctXFf4RPs6Vu2wQKizqfcVQleV5BefzVhpGGVCBv49P8+hqkLKt3QRuqoTf4rVkNLREuQNPUitMjHYrQHD9nNLXYH/QLQZtZYFic7PORZNraFjh1Fq5ZOGd9+XHzeh4UoWW/VUuWSEzTyxbUx8VP/S4CTuq89si7E/xJitZQJuhRpjSMP0OcGOFhkUCx9eNeP9U1YKkCmrEyTcxppIV91Rzylf5D8g/CF5//fj1vnnTIPD07oDseRXTuYZzFI2CDO2G9ZTIfx/1HvahnFClXHcDrpOYW2Is+bMmQJAOtHkGat5VIMcB8wOLeDfENolZEdl9zFJh2nzo+lzYKfsNcH4flufN2x/mwvqMx0NhmTzG9RAVJdYFEIfH3dU9rAdPrKVH7BvYCiuiu56V5a8k+CqZ+ZKTEP2CK67FRMl86aNpXvsWUUWwNW2dPsyd2rNucMaib/4qn7AkNQ=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
