services:
  frontend:
    name: frontend
    namespace: feedback-services
    replicas: 3
    image: bhatvinay7/reach-frontend:afee96341f508f832b3e8378d2831d63e4a4cb0c
    port: 80
    targetPort: 3000
    nodePort: 30080
    secretRef: frontend-sealed-secret
    dockersecretRef: docker-sealed-secret
  backend:
    name: backend
    namespace: feedback-services
    replicas: 2
    image: bhatvinay7/reach-backend:afee96341f508f832b3e8378d2831d63e4a4cb0c
    port: 80
    targetPort: 8000
    nodePort: 30081
    secretRef: backend-sealed-secret
    dockersecretRef: docker-sealed-secret
  ws-server:
    name: ws-server
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/ws-server:afee96341f508f832b3e8378d2831d63e4a4cb0c
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret
  kafka_consumer1:
    name: kafka_consumer1
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/kafka_consumer1:afee96341f508f832b3e8378d2831d63e4a4cb0c
    port: 80
    targetPort: 3005
    nodePort: 30083
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
  kafka_consumer2:
    name: kafka_consumer2
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/kafka_consumer2:afee96341f508f832b3e8378d2831d63e4a4cb0c
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
