services:  
  - name: frontend
    namespace: feedback-services
    replicas: 3
    image: bhatvinay7/reach-frontend:23a8a90cb9af2ea2af5fb20a2cd8bfe7bd280033
    port: 80
    targetPort: 3000
    nodePort: 30080
    secretRef: frontend-sealed-secret
    dockersecretRef: docker-sealed-secret

  
  - name: backend
    namespace: feedback-services
    replicas: 2
    image: bhatvinay7/reach-backend:23a8a90cb9af2ea2af5fb20a2cd8bfe7bd280033
    port: 80
    targetPort: 8000
    nodePort: 30081
    secretRef: backend-sealed-secret
    dockersecretRef: docker-sealed-secret

  
  - name: ws-server
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/ws-server:23a8a90cb9af2ea2af5fb20a2cd8bfe7bd280033
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret

  
  - name: kafka_consumer1
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/kafka_consumer1:23a8a90cb9af2ea2af5fb20a2cd8bfe7bd280033
    port: 80
    targetPort: 3005
    nodePort: 30083
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret

  
  - name: kafka_consumer2
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/kafka_consumer2:23a8a90cb9af2ea2af5fb20a2cd8bfe7bd280033
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
