services:
  frontend:
    name: frontend
    namespace: feedback
    replicas: 3
    image: reach-frontend:8aad8c64c8b6dd064acaf4a8219512400ef3d0fc
    port: 80
    targetPort: 3000
    nodePort: 30080
    secretRef: frontend-sealed-secret
    dockersecretRef: docker-sealed-secret
  backend:
    name: backend
    namespace: feedback
    replicas: 2
    image: reach-backend:8aad8c64c8b6dd064acaf4a8219512400ef3d0fc
    port: 80
    targetPort: 8000
    nodePort: 30081
    secretRef: backend-sealed-secret
    dockersecretRef: docker-sealed-secret
  ws-server:
    name: ws-server
    namespace: feedback
    replicas: 1
    image: ws-server:8aad8c64c8b6dd064acaf4a8219512400ef3d0fc
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret
  kafka_consumer1:
    name: kafka_consumer1
    namespace: feedback
    replicas: 1
    image: kafka_consumer1:8aad8c64c8b6dd064acaf4a8219512400ef3d0fc
    port: 80
    targetPort: 3005
    nodePort: 30083
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
  kafka_consumer2:
    name: kafka_consumer2
    namespace: feedback
    replicas: 1
    image: kafka_consumer2:8aad8c64c8b6dd064acaf4a8219512400ef3d0fc
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
