{{- range $key, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $svc.name }}
  namespace: {{ $svc.namespace }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
    spec:
      containers:
        - name: {{ $svc.name }}
          image: {{ $svc.image }}
          ports:
            - containerPort: {{ $svc.targetPort }}
          envFrom:
            - secretRef:
                name: {{ $svc.secretRef }}
      imagePullSecrets:
        - name: {{ svc.dockersecretRef }}          
---
{{- end }}
