services:
  - name: frontend
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-frontend:b9a884f2f960a32a45cc76879855e0fdb6e0f892
    port: 80
    targetPort: 3000
    nodePort: 30080
    secretRef: frontend-sealed-secret
    dockersecretRef: docker-sealed-secret
